a2lix_translation_form:
  locale_provider: default
  locales: '%app_locales_array%'
  default_locale: '%locale%'
  required_locales: '%app_locales_array%'
  templating: "@A2lixTranslationForm/bootstrap_5_layout.html.twig"